apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: "6.7.0"
    helm.sh/chart: grafana-5.7.10
  name: loki-grafana
  namespace: loki
spec:
  type: ClusterIP
  ports:
  - name: service
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/name: grafana
