apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Simone
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/version: 2.6.1
    helm.sh/chart: loki-distributed-0.63.2
  name: loki-loki-distributed-distributor-node-port
  namespace: loki
spec:
  type: NodePort
  ports:
    - name: http
      port: 3100
      targetPort: http
    - name: grpc
      port: 9095
      targetPort: grpc
  selector:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-distributed
