apiVersion: v1
kind: Service
metadata:
  name: syslog
  namespace: loki
spec:
  type: NodePort
  ports:
  - nodePort: 31514
    port: 1514
  selector:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail